---
- hosts: db
  become: yes
  tasks:
    - name: 'Instalação de pacotes DB'
      apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present
          #- name: 'Download e extração DB'
          #unarchive: 
          #src: https://github.com/rogerramossilva/devops/raw/master/db.zip
          #dest: /tmp
          #remote_src: yes
    - name: 'Criando DB Backup'
      mysql_db:
        name: backup
        login_user: root
        login_password: ""
        state: present
          #- name: 'Importação base de dados backup.sql'
          #mysql_db:
          #login_user: root
          #login_password: ""
          #state: import
          #name: backup
          #target: /tmp/backup.sql
    - name: 'Criação e Usuário Express no MySQL'
      mysql_user:
        host: '%'
        login_user: root
        login_password: ""
        name: express
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: present
        column_case_sensitive: false
    - name: 'Substituir bind do MySQL'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart MySQL
  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
        enabled: yes    
